// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/AsymmetricPanel.tsx": () => import("../components/mockups/login-variants/AsymmetricPanel.tsx"),
  "./components/mockups/login-variants/DashboardPreview.tsx": () => import("../components/mockups/login-variants/DashboardPreview.tsx"),
  "./components/mockups/login-variants/Institutional.tsx": () => import("../components/mockups/login-variants/Institutional.tsx"),
  "./components/mockups/login-variants/MinimalAuthority.tsx": () => import("../components/mockups/login-variants/MinimalAuthority.tsx"),
  "./components/mockups/login-variants/ShiftAware.tsx": () => import("../components/mockups/login-variants/ShiftAware.tsx"),
  "./components/mockups/login-variants/SplitScreen.tsx": () => import("../components/mockups/login-variants/SplitScreen.tsx")
};
